blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^(?:index/)?$', views.index, name='index'),
    url(r'^index/(?P<page>\d+)/$', views.index, name='index-with-page'),

    url(r'^post/(?P<slug>[\w-]+)/$', views.post, name='post'),

    url(r'^category/(?P<slug>[\w-]+)/$', views.category, name='category'),
    url(r'^category/(?P<slug>[\w-]+)/(?P<page>\d+)/$', views.category,
        name='category-with-page'),

    url(r'^tag/(?P<slug>[\w-]+)$', views.tag, name='tag'),
    url(r'^tag/(?P<slug>[\w-]+)/(?P<page>\d+)/$', views.tag,
        name='tag-with-page'),

    url(r'^search/$', view=views.search, name='search'),

    url(r'^share/(?P<slug>[\w-]+)/$', views.share, name='share')
]

zvz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

handler404 = 'zvz.views.handler404'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^githook/', views.githook),
    url(r'', include('blog.urls', namespace='blog')),

    url(r'^favicon.ico/?$', views.icon, name='icon'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


TAG_MAX_LENGTH = 20
CATEGORY_MAX_LENGTH = 40
NICKNAME_MAX_LENGTH = 40
TITLE_MAX_LENGTH = 50
REASON_MAX_LENGTH = 255

CN_TO_EN_RADIO = 2


class Tag(models.Model):
    name = models.CharField(max_length=TAG_MAX_LENGTH)
    slug = models.SlugField(max_length=TAG_MAX_LENGTH * CN_TO_EN_RADIO)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=CATEGORY_MAX_LENGTH)
    slug = models.SlugField(max_length=CATEGORY_MAX_LENGTH * CN_TO_EN_RADIO)
    parent = models.ForeignKey('self', null=True, blank=True,related_name='children')

    def __str__(self):
        return self.name


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=NICKNAME_MAX_LENGTH)
    sign = models.TextField()

    def __str__(self):
        return '{self.nickname}({self.id})'.format(self=self)


class Post(models.Model):
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    slug = models.SlugField(max_length=TITLE_MAX_LENGTH * CN_TO_EN_RADIO)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.TextField()
    tags = models.ManyToManyField(Tag, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    pub_date = models.DateTimeField('publish date', auto_now_add=True)
    last_mod = models.DateTimeField('last modify date', auto_now=True)
    isDraft = models.BooleanField(default=False)

    view_times = models.IntegerField(default=0)
    share_times = models.IntegerField(default=0)

    def __str__(self):
        return "{self.title} - {self.author.nickname}".format(self=self)


class Modification(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    reason = models.CharField(max_length=REASON_MAX_LENGTH)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return "{self.reason} at {self.time}".format(self=self)


class Comment(models.Model):
    nickname = models.CharField(max_length=NICKNAME_MAX_LENGTH)
    email = models.EmailField()
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE,
                               related_name='children',
                               null=True, default=None, blank=True)
    time = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(Author, on_delete=models.SET_NULL,
                             null=True, default=None, blank=True)
    floor = models.IntegerField(default=0)

    def __str__(self):
        return '{self.nickname}: {self.content}'.format(self=self)


class GithubHookSecret(models.Model):
    secret = models.CharField(max_length=255)

blog/forms.py
from django import forms


class SearchFrom(forms.Form):
    keyword = forms.CharField(label='', max_length=255, required=True,
                              widget=forms.TextInput(attrs={
                                  'class': 'search-keyword',
                              }))

blog/views.py
import math

from django.http import HttpResponse, HttpRequest, Http404
from django.core.urlresolvers import reverse
from django.db.models import Q, F
from django.shortcuts import render, get_object_or_404, redirect

from .models import Post, Tag, Category, Comment
from .apps import BlogConfig
from .forms import SearchFrom

Conf = BlogConfig.blog_settings


def get_item_in_page_or_404(the_list: list, page: str):
    try:
        page = int(page)
    except ValueError:
        raise Http404()

    if page <= 0:
        raise Http404()

    list_length = len(the_list)

    max_page_number = math.ceil(list_length / Conf['post_per_page'])
    max_page_number = 1 if max_page_number == 0 else max_page_number

    if page > max_page_number:
        raise Http404()

    start = Conf['post_per_page'] * (page - 1)
    end = start + Conf['post_per_page']

    return the_list.order_by('-pub_date')[start:end], page, max_page_number


def filter_post_list_by_user(the_list, user):
    if user.is_authenticated():  # is user
        if user.is_superuser:  # is Su
            return the_list
        elif user.author:  # is an author
            return the_list.exclude(Q(isDraft=True), ~Q(author=user.author))
        else:  # normal user
            return the_list.exclude(isDraft=True)
    else:
        return the_list.exclude(isDraft=True)


def has_permission_access_post(user, the_post):
    if not the_post.isDraft:
        return True
    if user.is_authenticated():
        if user.is_superuser:
            return True
        if user is the_post.author:
            return True
    return False


def index(req: HttpRequest, page: str = '1') -> HttpResponse:
    post_list = filter_post_list_by_user(Post.objects.all(), req.user)
    post_list, page, max_page = get_item_in_page_or_404(post_list, page)
    tags = Tag.objects.all()
    return render(req, 'blog/index.html', {
        'page': page,
        'max_page': max_page,
        'posts': post_list,
        'tags': tags
    })


def post(req: HttpRequest, slug: str) -> HttpResponse:
    the_post = get_object_or_404(Post, slug=slug)
    user = req.user

    if has_permission_access_post(user, the_post):
        the_post.view_times = F('view_times') + 1
        the_post.save()
        the_post.refresh_from_db()
        return render(req, 'blog/post.html', {
            'post': the_post,
        })

    raise Http404()


def category(req: HttpRequest, slug: str, page: str = '1') -> HttpResponse:
    the_category = get_object_or_404(Category, slug=slug)

    post_list = filter_post_list_by_user(
        Post.objects.filter(category__slug=slug), req.user)
    post_list, page, max_page = get_item_in_page_or_404(post_list, page)

    return render(req, 'blog/category.html', {
        'category': the_category,
        'posts': post_list,
        'page': page,
        'max_page': max_page,
        'tags': Tag.objects.all(),
    })


def tag(req: HttpRequest, slug: str, page: str = '1') -> HttpResponse:
    the_tag = get_object_or_404(Tag, slug=slug)

    post_list = filter_post_list_by_user(
        Post.objects.filter(tags__slug__contains=slug), req.user)
    post_list, page, max_page = get_item_in_page_or_404(post_list, page)

    return render(req, 'blog/tag.html', {
        'tags': Tag.objects.all(),
        'tag': the_tag,
        'posts': post_list,
        'page': page,
        'max_page': max_page,
    })


def search(req: HttpRequest):

    if req.method == 'GET':
        form = SearchFrom(req.GET, auto_id='%s')
        if form.is_valid():
            page = req.GET.get('page', '1')
            posts = Post.objects.filter(Q(title__contains=form.cleaned_data['keyword']) |
                                        Q(content__contains=form.cleaned_data['keyword']))
            posts = filter_post_list_by_user(posts, req.user)
            result_amount = len(posts)
            posts, page, max_page = get_item_in_page_or_404(posts, page)

            return render(req, 'blog/search.html', {
                'posts': posts,
                'keyword': form.cleaned_data['keyword'],
                'page': page,
                'max_page': max_page,
                'result_amount': result_amount,
            })
        else:
            return HttpResponse('参数填的不对不能搜哒！')


def share(req: HttpRequest, slug: str):
    the_post = get_object_or_404(Post, slug=slug)
    the_post.share_times = F('share_times') + 1
    the_post.save()
    post_url = req.build_absolute_uri(
        reverse('blog:post', kwargs={
            'slug': the_post.slug,
        }))
    url = 'http://www.jiathis.com/send/' \
          '?webid=tsina&url={0}&title=分享@7sDream 的文章：{1}'.format(
            post_url,
            the_post.title)

    return redirect(url)

blog/templates/blog/base_site.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    {% block meta %}
    {% endblock %}
    <meta name="google-site-verification" content="BazmSJ55LY7H3RD6ttelAsE8PmOPjhkFnDdIjFMCiJE" />
    <title>{{ blog_conf.name }} - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css"
          href="{% static 'blog/css/base_site.css' %}"/>
    <link href="//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css"
          rel="stylesheet">
    {% block css %}
    {% endblock css %}
</head>
<body>
<header>
    <div class="top-z-container">
        <div class="blur-top-image"></div>
        <div id="top-bar">
            <nav class="left-box">
                <ul>
                    <li>
                        <a href="{% url 'blog:index' %}">{{ blog_conf.name }}</a> - {{ blog_conf.description }}
                    </li>
                </ul>
            </nav>
            {% if user.is_authenticated %}
                <nav class="right-box">
                    <ul>
                        <li>欢迎 <a href="#">{{ user.username }}</a></li>
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
    <div id="top-image"></div>
    <nav class="nav-wrapper">
        <ul class="category-list">
            <li>
                <a href="{% url 'blog:index' %}">
                    <span>首页</span>
                    <div class="menu-icon-wrapper">
                        <span class="menu-icon icon-no-bg-color fa fa-home"></span>
                    </div>
                </a>
            </li>
            {% for category in categories %}
                <li onmouseover="show_menu(this)" onmouseout="hide_menu(this)">
                    <a href="{% url 'blog:category' category.slug %}">
                        <div class="menu-icon-wrapper">
                            <span class="menu-icon">{{ category.children.count }}</span>
                        </div>
                        {{ category.name }}
                    </a>
                    {% if category.children %}
                        <ul class="drop-down">
                            {% for sub_category in category.children.all %}
                                <li>
                                    <a href="{% url 'blog:category' sub_category.slug %}">{{ sub_category.name }}</a>
                                    <span class="menu-icon">{{ sub_category.post_set.count }}</span>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endfor %}
            {% if about %}
                <li>
                    <a href="{% url 'blog:post' slug='about' %}">
                        <span>关于</span>
                        <div class="menu-icon-wrapper">
                            <span class="menu-icon icon-no-bg-color fa fa-info"></span>
                        </div>
                    </a>
                </li>
            {% endif %}
            <form id="search-form" method="GET" action="/search/"  onsubmit="return search_validator(this);">
                {{ search_form }}
                <button class="search-commit" type="submit">搜索</button>
            </form>
        </ul>
    </nav>
</header>
<main>
    <div id="main">
        {% block body %}
        {% endblock %}
    </div>
</main>
<footer>
    <div id="foot">
        {% block foot %}
            <div class="footer">
                <span>
                    Powered by:
                    <a href="https://www.python.org" target="_blank">Python</a>,
                    <a href="https://www.djangoproject.com/" target="_blank">Django</a>,
                    <a href="https://www.sqlite.org/" target="_blank">SQLite</a>,
                    <a href="http://www.apache.org/" target="_blank">Apache</a>
                </span>
                <br>
                <span>
                    Special thanks:
                    <a href="https://www.jetbrains.com/pycharm/" target="_blank">PyCharm</a>,
                    <a href="https://www.google.com/chrome/" target="_blank">Chrome</a>,
                    <a href="https://portal.qiniu.com/signup?code=3la79ggdylxea" target="_blank">Qiniu</a>,
                    <a href="https://m.do.co/c/a0a152628559" target="_blank">DigitalOcean</a>
                </span>
            </div>
        {% endblock %}
    </div>
</footer>
<div id="to-top">
    <a href="" onclick="scroll_to_top(0.9); return false;">
        <span class="fa fa-chevron-circle-up"></span>
    </a>
</div>
</body>
<script src="{% static 'blog/js/base_site.js' %}"> </script>
{% block scripts %}
{% endblock %}
</html>

blog/templates/blog/category.html
{% extends 'blog/index.html' %}

{% block title %}目录 - {{ category.name }}{% endblock %}

{% block before_posts %}
    <div class="category-card">
        <div class="category-info">
            <h2>当前目录：{{ category.name }}</h2>
            <p>
                父目录：
                {% if category.parent %}
                    <a href="{% url 'blog:category' slug=category.parent.slug %}">{{ category.parent.name }}</a>
                {% else %}
                    无
                {% endif %}
            </p>
            <p>
                子目录：
                {% for child in category.children.all %}
                    <span><a href="{% url 'blog:category' child.slug %}">{{ child.name }}</a> </span>
                {% empty %}
                    无
                {% endfor %}
            </p>
        </div>
    </div>
{% endblock %}

{% block last_page_url %}
    {% url 'blog:category-with-page' slug=category.slug page=page|add:'-1' %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:category-with-page' slug=category.slug page=page|add:'1' %}
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base_site.html" %}

{% load staticfiles %}

{% block title %}首页{% if page > 1 %} - 第 {{ page }} 页{% endif %}{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'blog/css/index.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'blog/css/self_card.css' %}"/>
{% endblock css %}

{% block body %}
    <div class="index-body-wrapper">
        <div class="post-list">
            {% block before_posts %}
            {% endblock %}
            {% for post in posts %}
                <div class="post">
                    <div class="content">
                        <div class="post-author-category">
                            <a class="author" href="#">
                                <span class="fa fa-user"> {{ post.author.nickname }}</span>
                            </a>
                            {% if post.category %}
                                <a href="{% url 'blog:category' post.category.slug %}">
                                    {{ post.category.name }}
                                </a>
                            {% else %}
                                <a>未分类</a>
                            {% endif %}
                        </div>
                        <h2>
                            <a href="{% url 'blog:post' post.slug %}#main">{{ post.title }}</a>
                        </h2>
                        <div class="summary">{{ post.content|truncatechars:200 }}...</div>
                    </div>
                    <div class="info">
                        <span class="meta-info fa fa-calendar">
                            {{ post.pub_date|date:"Y-m-d" }}
                        </span>
                        <span class="meta-info fa fa-clock-o">
                            {{ post.pub_date|date:"H:i:s" }}
                        </span>
                        {% if post.isDraft %}
                            <span class="meta-info fa fa-file-text">Draft!</span>
                        {% endif %}
                        <div class="right">
                            <span class="meta-info fa fa-eye"> {{ post.view_times }}</span>
                            <span class="meta-info fa fa-comment"> {{ post.comment_set.count }}</span>
                            <a href="{% url 'blog:share' post.slug %}" target="_blank"><span class="meta-info fa fa-share"> {{ post.share_times }}</span></a>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="post">
                    <div class="content">
                        <h2>这里暂时没有文章哟~</h2>
                        <p>怎么办呢~~少女思考中……</p>
                    </div>
                </div>
            {% endfor %}
            <div class="turn-page-wrapper">
                <div class="turn-page">
                    {% if page != 1 %}
                        <a class="left" href="{% block last_page_url %}{% url 'blog:index-with-page' page=page|add:'-1' %}{% endblock %}">
                            <span class="fa fa-angle-left"> LAST</span>
                        </a>
                    {% endif %}
                    {{ page }}
                    {% if page != max_page %}
                        <a class="right" href="{% block next_page_url %}{% url 'blog:index-with-page' page=page|add:'1' %}{% endblock %}">
                            NEXT<span class="fa fa-angle-right"></span>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="right-wrapper">
            {% include 'blog/info_card.html' %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="//cdn.bootcss.com/markdown.js/0.5.0/markdown.min.js"></script>
    <script>
        function md2html(elem) {
            md = elem.textContent;
            elem.textContent = '';
            elem.insertAdjacentHTML('afterBegin', markdown.toHTML(md));
            Array.prototype.slice.call(elem.querySelectorAll('img')).forEach(function (elem) {
                elem.parentNode.removeChild(elem);
            });
        }

        function all_md_to_html() {
            Array.prototype.slice.call(document.querySelectorAll('.summary')).forEach(md2html)
        }

        if (window.addEventListener) {
            window.addEventListener('DOMContentLoaded', all_md_to_html, false)
        }
        else if (window.attachEvent) {
            window.attachEvent('onload', all_md_to_html)
        }
    </script>
{% endblock %}

blog/templates/blog/info_card.html
{% load staticfiles %}

<div class="right-card">
    <div class="user-icon-wrapper">
        <a><img src="{% static blog_conf.owner_avatar %}" width="96px"
                height="96px"></a>
        <h2><a>{{ blog_conf.owner_name }}</a></h2>
    </div>
    <div class="sign">
        <p>{{ blog_conf.owner_sign }}</p>
    </div>
    <div class="self-info">
        <ul>
            {% for info in blog_conf.self_infos %}
                <li><a href="{{ info.url }}">{{ info.name }}</a><span
                        class="right-icon fa fa-{{ info.icon }}"></span></li>
            {% endfor %}
        </ul>
    </div>
    {% if tags %}
        <div class="tags">
        {% for tag in tags %}
            <a href="{% url 'blog:tag' tag.slug %}">{{ tag.name }}</a>
        {% endfor %}
    </div>
    {% endif %}
    <div class="what-i-use">
        @<a href="#">7sDream</a><br>
        Powered by <a href="https://www.djangoproject.com/">Django</a>
    </div>
</div>

blog/templates/blog/post.html
{% extends "blog/base_site.html" %}

{% load staticfiles %}

{% block meta %}
    <meta name="author" content="{{ post.author.nickname }}">
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'blog/css/post.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'blog/css/self_card.css' %}"/>
{% endblock %}

{% block title %}文章 - {{ post.title }}{% endblock %}

{% block body %}
    <div class="post-body-wrapper">
        <div class="post-wrapper">
            <div class="post">
                <h1 id="title">{{ post.title }}</h1>
                <div id="content">{{ post.content }}</div>
            </div>
            <div id="post-meta">
                <span class="meta-info fa fa-calendar">
                    {{ post.pub_date|date:"Y-m-d" }}
                </span>
                <span class="meta-info fa fa-clock-o">
                    {{ post.pub_date|date:"h:i:s" }}
                </span>
                {% if post.isDraft %}
                    <span class="meta-info fa fa-file-text">Draft!</span>
                {% endif %}
                <div class="right">
                    <span class="meta-info fa fa-eye"> {{ post.view_times }}</span>
                    <span class="meta-info fa fa-comment"> {{ post.comment_set.count }}</span>
                    <a href="{% url 'blog:share' post.slug %}" target="_blank"><span class="meta-info fa fa-share"> {{ post.share_times }}</span></a>
                </div>
            </div>
        </div>
        <div class="right-wrapper">
            {% include 'blog/info_card.html' %}
            <div class="right-card" id="toc-card">
                <h2>Toc</h2>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="//cdn.bootcss.com/markdown.js/0.5.0/markdown.min.js"></script>
    <script src="{% static 'blog/js/post.js' %}"></script>
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/index.html' %}

{% block title %}搜索 - {{ keyword }}{% endblock %}

{% block before_posts %}
    <div class="category-card">
        <div class="category-info">
            <h2>关键词：{{ keyword }}</h2>
            <p>
                搜索到结果：{{ result_amount }} 项
            </p>
        </div>
    </div>
{% endblock %}

{% block last_page_url %}{% url 'blog:search' %}?keyword={{ keyword }}&page={{ page|add:'-1' }}{% endblock %}

{% block next_page_url %}{% url 'blog:search' %}?keyword={{ keyword }}&page={{ page|add:'1' }}{% endblock %}

blog/templates/blog/tag.html
{% extends 'blog/index.html' %}

{% block title %}标签 - {{ tag.name }}{% endblock %}

{% block before_posts %}
    <div class="category-card">
        <div class="category-info">
            <h2>标签：{{ tag.name }}</h2>
            <p>
                所有标签：
                {% for child in tags %}
                    <span><a href="{% url 'blog:tag' child.slug %}">{{ child.name }}</a> </span>
                {% endfor %}
            </p>
        </div>
    </div>
{% endblock %}

{% block last_page_url %}{% url 'blog:tag-with-page' slug=tag.slug page=page|add:'-1' %}{% endblock %}

{% block next_page_url %}{% url 'blog:tag-with-page' slug=tag.slug page=page|add:'1' %}{% endblock %}